[package]
name = "healthchecks"
version = "1.0.2-alpha.0"
authors = ["Harsh Shandilya <me@msfjarvis.dev>"]
edition = "2018"
description = "Simple library to notify healthchecks.io from inside applications"
repository = "https://github.com/msfjarvis/healthchecks-rs"
homepage = "https://github.com/msfjarvis/healthchecks-rs"
license = "MIT/Apache-2.0"
keywords = ["healthchecks"]
readme = "README.md"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ureq = { version = "1.3.0", features = [ "json" ] }
uuid = { version = "0.8.1", default-features = false, features = [ "v1" ] }
anyhow = "1.0.31"
serde = { version = "1.0.114", default-features = false, features = ["derive"] }
serde_json = "1.0.56"

[badges]
maintenance = { status = "actively-developed" }
