version: 2
updates:
  - package-ecosystem: "cargo"
    directory: "/healthchecks"
    schedule:
      interval: "weekly"
  - package-ecosystem: "cargo"
    directory: "/monitor"
    schedule:
      interval: "weekly"
