[package]
name = "healthchecks"
version = "0.1.0"
authors = ["Harsh Shandilya <me@msfjarvis.dev>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ureq = "1.1.1"
uuid = { version = "0.8.1", default-features = false, features = [ "v1" ] }
