[package]
name = "healthchecks-monitor"
version = "1.0.0"
authors = ["Harsh Shandilya <me@msfjarvis.dev>"]
edition = "2018"
description = "Report results of arbitrary commands to healthchecks.io"
repository = "https://github.com/msfjarvis/healthchecks-rs"
homepage = "https://github.com/msfjarvis/healthchecks-rs"
license = "MIT/Apache-2.0"
keywords = ["healthchecks"]
readme = "README.md"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
healthchecks = { path = "../healthchecks" }
clap = { version = "2.33.1", default-features = false, features = ["suggestions", "color"] }
pretty-exec-lib = "0.0.17"

[badges]
maintenance = { status = "actively-developed" }
