[package]
name = "healthchecks-monitor"
version = "1.0.2-alpha.0"
authors = ["Harsh Shandilya <me@msfjarvis.dev>"]
edition = "2018"
description = "Report results of arbitrary commands to healthchecks.io"
repository = "https://github.com/msfjarvis/healthchecks-rs"
homepage = "https://github.com/msfjarvis/healthchecks-rs"
license = "MIT/Apache-2.0"
keywords = ["healthchecks"]
readme = "README.md"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
healthchecks = { path = "../healthchecks", version = "^1.0.2-alpha.0"}
clap = { version = "2.33.1", default-features = false, features = ["suggestions", "color"] }
serde = { version = "1.0.114", default-features = false, features = ["derive"] }
anyhow = "1.0.31"
envy = "0.4.1"
execute = "0.2.6"

[badges]
maintenance = { status = "actively-developed" }
