on:
  push:
    branches:
      - develop

name: Verify nix-shell config
jobs:
  check:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v1

    - uses: actions/cache@v2
      with:
        path: |
          ~/.cargo/registry
          ~/.cargo/git
          target
        key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

    - name: Install Nix
      uses: cachix/install-nix-action@v10
      with:
        nix_path: nixpkgs=channel:nixos-unstable

    - name: Enter nix-shell
      run: nix-shell --pure

    - name: Run cargo check
      run: cargo check
